name: Run Python Tests

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

  push:
    branches: [ "main" ]
    tags:     [ "v*" ]


jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install ".[test]"
        uv pip install pytest

    - name: Run tests
      env:  
        LLAMA_API_KEY: ${{ secrets.LLAMA_API_KEY }}
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        NEO4J_URI: ${{ secrets.NEO4J_URI }}
        NEO4J_USER: ${{ secrets.NEO4J_USER }}
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      run: uv run pytest
